server:
  port: 8888
spring:
  application:
    name: simple-spark-etl
  session-config:
    "[spark.sql.shuffle.partitions]": 10
    "[spark.executor.memory]": 2g
spark-cluster:
  sparkHome: /usr/local/spark-2.4.7-bin-hadoop2.7
  master: spark://rongshen-ThinkPad-T420:7077
  serviceJar: /home/rongshen/projects/simple-spark-etl/simple-spark-etl-job/build/libs/simple-spark-etl-job-0.0.1-SNAPSHOT.jar
  jars: /home/rongshen/projects/simple-spark-etl/country-weather-etl-job/build/libs/country-weather-etl-job-0.0.1-SNAPSHOT.jar
